// class RidesModel{
//  var   id,
//  user_id,
//  username,
//  uneaque_id,
//  purpose,
//  pickup_area,
//  pickup_date,
//  drop_area,
//  pickup_time,
//  area,
//  landmark,
//  pickup_address,
//  drop_address,
//  taxi_type,
//  departure_time,
//  departure_date,
//  return_date,
//  flight_number,
//  package,
//  promo_code,
//  distance,
//  amount,
//  paid_amount,
//  address,
//  transfer,
//  item_status,
//  transaction,
//  payment_media,
//  km,
//  timetype,
//  assigned_for,
//  is_paid_advance,
//  status,
//  latitude,
//  longitude,
//  date_added,
//  drop_latitude,
//  drop_longitude,
//  booking_type,
//  accept_reject,
//  created_date;
//
//  RidesModel(
//       this.id,
//       this.user_id,
//       this.username,
//       this.uneaque_id,
//       this.purpose,
//       this.pickup_area,
//       this.pickup_date,
//       this.drop_area,
//       this.pickup_time,
//       this.area,
//       this.landmark,
//       this.pickup_address,
//       this.drop_address,
//       this.taxi_type,
//       this.departure_time,
//       this.departure_date,
//       this.return_date,
//       this.flight_number,
//       this.package,
//       this.promo_code,
//       this.distance,
//       this.amount,
//       this.paid_amount,
//       this.address,
//       this.transfer,
//       this.item_status,
//       this.transaction,
//       this.payment_media,
//       this.km,
//       this.timetype,
//       this.assigned_for,
//       this.is_paid_advance,
//       this.status,
//       this.latitude,
//       this.longitude,
//       this.date_added,
//       this.drop_latitude,
//       this.drop_longitude,
//       this.booking_type,
//       this.accept_reject,
//       this.created_date);
// }

class RidesModel {
  String taxi_id,
      vendorId,
      cartype,
      carmodel,
      intialkm,
      intailrate,
      base_fare,
      time_cahrge,
      rate_per_km,
      main_rate_per_km,
      image,
      serge,
      gst,
      catType,
      minFare,
      cancellation_charges;
  List surge_charge;
  String admin_commission;
  String fuel_type,
      seating_capacity,
      insurance_expiry,
      pollution_expiry,
      vehicle_no,
      luggage_carrier,
      luggage_capacity,
      distance,
      extra_price,
      tax_amount,
      service_charge,
      cancellation_charge;
  RidesModel(
      this.taxi_id,
      this.vendorId,
      this.cartype,
      this.carmodel,
      this.intialkm,
      this.intailrate,
      this.base_fare,
      this.time_cahrge,
      this.rate_per_km,
      this.main_rate_per_km,
      this.image,
      this.serge,
      this.gst,
      this.surge_charge,
      this.catType,
      this.minFare,
      this.cancellation_charges,
      this.admin_commission,
      this.fuel_type,
      this.seating_capacity,
      this.insurance_expiry,
      this.pollution_expiry,
      this.vehicle_no,
      this.luggage_carrier,
      this.luggage_capacity,
      this.distance,
      this.extra_price,
      this.tax_amount,
      this.cancellation_charge, this.service_charge);
}
